<?php

/**
 * @file Drupal hook implementations and utility functions for the vopros_search module
 */

/**
 * Implements hook_facetapi_facet_info_alter().
 */
function vopros_search_facetapi_facet_info_alter(array &$facet_info, array $searcher_info) {
  $facet_info['question:question_status']['map callback'] = '_vopros_question_status';
  $facet_info['question:question_status_reason']['map callback'] = '_vopros_question_status_reason';
  $facet_info['question:user_gender']['map callback'] = '_vopros_question_user_gender';
  $facet_info['question:user_answer_preference']['map callback'] = '_vopros_question_user_answer_preference';
}

/**
 * Implements hook_views_data_alter().
 */
function vopros_search_views_data_alter(&$data) {
  if (!empty($data['search_api_index_vopros_answer_question']['question_question_status']['field']['handler'])) {
    $data['search_api_index_vopros_answer_question']['question_question_status']['field']['handler'] = 'VoprosSeachSearchApiViewsHandlerField';
  }
  if (!empty($data['search_api_index_vopros_answer_question']['question_question_status_reason']['field']['handler'])) {
    $data['search_api_index_vopros_answer_question']['question_question_status_reason']['field']['handler'] = 'VoprosSeachSearchApiViewsHandlerField';
  }
  if (!empty($data['search_api_index_vopros_answer_question']['question_created']['field'])) {
    $data['search_api_index_vopros_answer_question']['question_created']['field']['handler'] = 'entity_views_handler_field_date';
  }
  if (!empty($data['search_api_index_vopros_answer_question']['user']['filter'])) {
    $data['search_api_index_vopros_answer_question']['user']['filter']['handler'] = 'SearchApiViewsHandlerFilterOptions';
    $profiles = profile2_load_multiple(FALSE, array('type' => 'vopros_user_librarian'));
    $options = vopros_user_get_librarians();
    // Sort the options.
    asort($options);
    $data['search_api_index_vopros_answer_question']['user']['filter']['options'] = $options;
  }
}

/**
 * Implements hook_views_api().
 */
function vopros_search_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'vopros_search') . '/includes/views',
  );
}

/**
 * Implements hook_enable().
 */
function vopros_search_enable() {
  if (!search_api_index_load_multiple(FALSE, array('machine_name' => 'vopros_answer_question'))) {
    $values = array(
      'name' => 'Vopros Answer and Question search index',
      'machine_name' => 'vopros_answer_question',
      'description' => t('An automatically created search index required to be able to use the search page create by Vopros search.'),
      'server' => NULL,
      'item_type' => 'vopros_answer',
      'options' => array(
        'cron_limit' => '100',
        'index_directly' => 1,
        'fields' => array(
          'answer_id' => array(
            'type' => 'integer',
          ),
          'question_id' => array(
            'type' => 'integer',
          ),
          'uid' => array(
            'type' => 'integer',
          ),
          'answer_content' => array(
            'type' => 'text',
            'boost' => '3.0',
          ),
          'created' => array(
            'type' => 'date',
          ),
          'changed' => array(
            'type' => 'date',
          ),
          'user' => array(
            'type' => 'integer',
            'entity_type' => 'user'
          ),
          'search_api_language' => array(
            'type' => 'string',
          ),
          'question:uid' => array(
            'type' => 'integer',
          ),
          'question:question_title' => array(
            'type' => 'text',
            'boost' => '2.0',
          ),
          'question:question_content' => array(
            'type' => 'text',
          ),
          'question:question_status' => array(
            'type' => 'string',
          ),
          'question:question_status_reason' => array(
            'type' => 'string',
          ),
          'question:question_deadline_timestamp' => array(
            'type' => 'date',
          ),
          'question:question_usage' => array(
            'type' => 'string',
          ),
          'question:question_note' => array(
            'type' => 'text',
            'boost' => '0.8',
          ),
          'question:user_name' => array(
            'type' => 'string',
          ),
          'question:user_email' => array(
            'type' => 'string',
          ),
          'question:user_postal_code' => array(
            'type' => 'string',
          ),
          'question:user_mobile_phone' => array(
            'type' => 'string',
          ),
          'question:user_age' => array(
            'type' => 'string',
          ),
          'question:user_gender' => array(
            'type' => 'string',
          ),
          'question:user_field_of_study' => array(
            'type' => 'string',
          ),
          'question:user_library' => array(
            'type' => 'string',
          ),
          'question:user_answer_preference' => array(
            'type' => 'string',
          ),
          'question:created' => array(
            'type' => 'date',
          ),
          'question:changed' => array(
            'type' => 'date',
          ),
          'question:subject_catagory' => array(
            'type' => 'list<integer>',
            'entity_type' => 'taxonomy_term'
          ),
          'question:vopros_editorial' => array(
            'type' => 'list<integer>',
            'entity_type' => 'taxonomy_term'
          ),
        ),
      ),
    );
    search_api_index_insert($values);
  }
}
