<?php

/**
 * Implements hook_menu().
 */
function vopros_statistics_menu() {
  $items['admin/vopros/statistics'] = array(
    'title' => 'Statistics',
    'description' => 'Display statistics about vopros questions and answers',
    'page callback' => 'vopros_statistics_year_view',
    'access arguments' => array('access vopros statistics'),
    'file' => 'vopros_statistics.admin.inc',
  );

  $items['admin/vopros/statistics/year'] = array(
    'title' => 'Year',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );


  $min_created = db_query("SELECT MIN(created) FROM {vopros_question}")->fetchField();

  foreach (range(date('Y', $min_created), date('Y', REQUEST_TIME)) as $year) {
    $items['admin/vopros/statistics/year/' . $year] = array(
      'title' => $year,
      'page callback' => 'vopros_statistics_year_view',
      'page arguments' => array(4),
      'access arguments' => array('access vopros statistics'),
      'file' => 'vopros_statistics.admin.inc',
      'type' => MENU_LOCAL_TASK,
      'weight' => -$year,
    );
  }

  $items['admin/vopros/statistics/year/' . $year]['type'] = MENU_DEFAULT_LOCAL_TASK;

  $items['admin/vopros/statistics/week'] = array(
    'title' => 'Week day',
    'page callback' => 'vopros_statistics_week_view',
    'access arguments' => array('access vopros statistics'),
    'file' => 'vopros_statistics.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/vopros/statistics/time'] = array(
    'title' => 'Time',
    'page callback' => 'vopros_statistics_time_view',
    'access arguments' => array('access vopros statistics'),
    'file' => 'vopros_statistics.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/vopros/statistics/qanda_service_name'] = array(
    'title' => 'Q and A service name',
    'page callback' => 'vopros_statistics_qanda_service_name_view',
    'access arguments' => array('access vopros statistics'),
    'file' => 'vopros_statistics.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function vopros_statistics_permission() {
  return array(
    'access vopros statistics' =>  array(
      'title' => t('Access statistics'),
      'description' => '',
    ),
  );
}

