<?php

/**
 * @file
 */

/**
 * Implements hook_menu().
 */
function vopros_menu() {
  // Top level "Vopros" container.
  return array(
    'admin/vopros' => array(
      'title' => 'Vopros',
      'description' => 'Administer vopros.',
      'page callback' => 'system_admin_menu_block_page',
      'access arguments' => array('access administration pages'),
      'file path' => drupal_get_path('module', 'system'),
      'file' => 'system.admin.inc',
      'weight' => -7,
    ),

    'admin/vopros/config' => array(
      'title' => 'Configuration',
      'description' => 'Configure settings and business rules for vopros.',
      'page callback' => 'system_admin_menu_block_page',
      'access arguments' => array('access administration pages'),
      'type' => MENU_NORMAL_ITEM,
      'weight' => 10,
      'file path' => drupal_get_path('module', 'system'),
      'file' => 'system.admin.inc',
    ),
  );

  return $items;
}

/**
 * Callback for getting entity properties
 */
function vopros_get_properties($entity, array $options, $name) {
  return $entity->{$name.'_id'};
}

/**
 * Callback for setting line item properties.
 */
function vopros_set_properties($entity, $name, $value) {
  return $entity->{$name.'_id'} = $value;
}

/**
 * Renders a View for display in some other element.
 *
 * @param $view_key
 *   The ID of the View to embed.
 * @param $display_id
 *   The ID of the display of the View that will actually be rendered.
 * @param $arguments
 *   An array of arguments to pass to the View.
 *
 * @return
 *   The rendered output of the chosen View display.
 */
function vopros_embed_view($view_id, $display_id = 'default', $arguments = array()) {
  // Load the cart line item View.
  $view = views_get_view($view_id);
  $view->set_display($display_id);

  // Set the specific line items for this order.
  $view->set_arguments($arguments);

  // Prepare and execute the View query.
  $view->pre_execute();
  $view->execute();

  // Return the rendered View.
  return $view->render();
}
