<?php

/**
 * @file
 * The vopros_log module creates a log entity that can be asociated to
 * questions or answers. These logs are for internal use only.
 */

/**
 * Implements hook_entity_info().
 */
function vopros_log_entity_info() {
  $return = array(
    'vopros_log' => array(
      'label' => t('Log', array(), array('context' => 'a vopros log')),
      'controller class' => 'VoprosLogEntityController',
      'base table' => 'vopros_log',
      // No revision table needed for logs.
      // Logs are simple and can't and shouldn't have fields.
      'fieldable' => FALSE,
      'entity keys' => array(
        'id' => 'log_id',
      ),
      'bundles' => array(
        'vopros_log' => array(
          'label' => t('Log', array(), array('context' => 'a vopros log')),
        ),
      ),
      'load hook' => 'vopros_log_load',
      'view modes' => array(
        'administrator' => array(
          'label' => t('Administrator'),
          'custom settings' => FALSE,
        ),
      ),
      'access callback' => 'vopros_log_access',
      'views controller class' => 'EntityDefaultViewsController',
    ),
  );

  return $return;
}

/**
 * Create a new log object
 */
function vopros_log_new($values = array()) {
  $default_values = array();
  $values += $default_values;
  return entity_create('vopros_log', $values);
}

/**
 * Save a log.
 *
 * @param $log
 *    The log object
 */
function vopros_log_save($log) {
  entity_save('vopros_log', $log);
}

/**
 * Loads an question by ID.
 *
 * @param $log_id
 *    The log id
 * @param $reset
 *   Whether to reset the internal log loading cache.
 *
 * @return A vopros log object or FALSE if no log was found.
 */
function vopros_log_load($log_id, $reset = FALSE) {
  $logs = vopros_log_load_multiple(array($log_id), array(), $reset);
  return $logs ? reset($logs) : FALSE;
}

/**
 * Loads multiple questions by ID or based on a set of matching conditions.
 *
 * @see entity_load()
 *
 * @param $log_ids
 *   An array of log IDs.
 * @param $conditions
 *   An array of conditions on the {vopros_log} table in the form
 *     'field' => $value.
 * @param $reset
 *   Whether to reset the internal log loading cache.
 *
 * @return
 *   An array of log objects indexed by log_id.
 */
function vopros_log_load_multiple($log_ids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('vopros_log', $log_ids, $conditions, $reset);
}

function vopros_log_form($form, &$form_state, $log = NULL, $question_id = NULL, $answer_id = NULL) {
  $form['quesiton_id'] = array(
    '#type' => 'value',
    '#value' => $question_id,
  );

  $form['answer_id'] = array(
    '#type' => 'value',
    '#value' => $answer_id,
  );

  $form['log_content'] = array(
    '#type' => 'textarea',
    '#title' => t('Internal log'),
    '#required' => TRUE,
    '#default_value' => $log ? $log->log_content : '',
  );

  $form['save'] = array(
    '#type' => 'submit',
    '#value' => t('Add log message'),
    '#ajax' => array(
      'callback' => 'vopros_log_form_ajax_submit',
    )
  );

  return $form;
}

/**
 * Handles saving the log.
 */
function vopros_log_form_ajax_submit(&$form, &$form_state) {
  $values = array(
    'question_id' => $form_state['values']['question_id'],
    'answer_id' => $form_state['values']['answer_id'],
    'log_content' => $form_state['values']['log_content'],
  );
  $log = vopros_log_new($values);
  //vopros_log_save($log);
  $commands = array();
  $commands[] = ajax_command_invoke('#edit-log-content', 'val', array(''));
  // TODO: Show to the user somehow that the log was saved.
  // TODO: Add the actual log to the "activity stream".
  return array('#type' => 'ajax', '#commands' => $commands);
}

/**
 * Implements hook_enyity_view_alter().
 */
function vopros_log_entity_view($entity, $type, $view_mode, $langcode) {
  if ($type == 'vopros_question' && $view_mode == 'administrator') {
    $entity->content['right']['log_form'] = drupal_get_form('vopros_log_form', NULL, $entity->question_id);
  }
}
