<?php

/**
 * Implementation of hook_nodeapi().
 */
function vopros_qna_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'insert':
    case 'update':
      // When an answer is saved, mark its question for reindexing.
      if (
        $node->type == 'vopros_answer' &&
        isset($node->field_answer_question_ref[0]['nid']) &&
        $node->field_answer_question_ref[0]['nid'] > 0
      ) {
        db_query("UPDATE {search_dataset} SET reindex = UNIX_TIMESTAMP() WHERE type = 'node' AND sid = %d",
          array(':nid' => $node->field_answer_question_ref[0]['nid']));
      }
      break;
    case 'update index':
      if ($node->type == 'vopros_question') {
        // CCK fields as the question reference on answer nodes have 
        // dynamic database schemas, so we rely on CCKs function to tell 
        // us which table and row to look in.
        static $database_info;
        if (!$database_info) {
          $field_data = content_fields('field_answer_question_ref', 'vopros_answer');
          $database_info = content_database_info($field_data);
        }

        // Get all the answers related to the question.
        $query = db_query("
          SELECT nid FROM " . $database_info['table'] . "
          WHERE " . $database_info['columns']['nid']['column'] . " = %d
        ", array(':nid' => $node->nid));

        $answer_markup = array();

        // Render each answer like _node_index_node() does.
        while ($nid = db_result($query)) {
          $answer = node_load($nid);

          // Set a flag to prevent the code below from preventing 
          // indexing of the answer.
          $answer->vopros_qna_build = TRUE;

          // Build the node body.
          $answer->build_mode = NODE_BUILD_SEARCH_INDEX;
          $answer = node_build_content($answer, FALSE, FALSE);
          $answer->body = drupal_render($answer->content);

          $text = '<h1>' . check_plain($answer->title) . '</h1>' . $answer->body;

          // Fetch extra data normally not visible
          $extra = node_invoke_nodeapi($answer, 'update index');
          foreach ($extra as $t) {
            $text .= $t;
          }

          $answer_markup[$nid] = $text;
        }

        // The return value is added to the index.
        return implode($answer_markup);
      }
      break;
    case 'view':
      if ($node->type == 'vopros_answer') {
        // Prevent the answers from being indexed by setting title and 
        // body to an empty string.
        if ($node->build_mode == NODE_BUILD_SEARCH_INDEX && !isset($node->vopros_qna_build)) {
          $node->title = '';
          $node->content = array();
        }
        // An answer node should not be viewable by itself. Instead, redirect 
        // to the answer on the question page.
        elseif ($a4 && // Node being viewed on a page by itself.
          isset($node->field_answer_question_ref[0]['nid']) &&
          $node->field_answer_question_ref[0]['nid'] > 0
        ) {
          $question_nid = (integer) $node->field_answer_question_ref[0]['nid'];
          drupal_goto('node/' . $question_nid, NULL, 'node-' .  $node->nid, 301);
        }
      }
    break;
  }
}

/**
 * Implementation of hook_link().
 */
function vopros_qna_link($type, $object, $teaser = FALSE) {
  $links = array();

  // Provide a link to answer the question for user with access.
  if ($type == 'node' && $object->type == 'vopros_question' &&
      user_access('create vopros_answer content')) {
    $links['vopros_answer_question'] = array(
      'title' => 'Besvar dette spørgsmål',
      'href' => 'node/add/vopros-answer',
      'query' => array('question' => $object->nid),
    );

    $links['vopros_edit_question'] = array(
      'title' => 'Redigér spørgsmålet',
      'href' => 'node/' . $object->nid . '/edit',
      'query' => drupal_get_destination,
    );
  }
  // Provide a link to edit the question when viewing the answer (since 
  // the normal links are not available, since the answer it not being 
  // viewed on a page by itself.
  elseif ($type == 'node' && $object->type == 'vopros_answer' &&
      node_access('update', $object)) {
    $links['vopros_edit_answer'] = array(
      'title' => 'Redigér dette svar',
      'href' => 'node/' . $object->nid . '/edit',
    );
  }

  return $links;
}

/**
 * Implementation of hook_form_alter().
 */
function vopros_qna_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'vopros_answer_node_form') {
    if (isset($_REQUEST['question']) && $_REQUEST['question'] > 0) {
      // If question is specified in the query parameters, set the 
      // default value for the selection widget to that question, and 
      // hide it with #access. #disabled does seem to work for CCK 
      // widgets like these.
      // This cannot be done with hook_form_FORM_ID_alter, since the CCK 
      // fields have not been added yet when that hook is run.
      $form['field_answer_question_ref'][0]['#default_value']['nid'] = (integer) $_REQUEST['question'];
      $form['field_answer_question_ref']['#access'] = FALSE;
    }

    // Get the nid form the question we're answering.
    $question = node_load($form['field_answer_question_ref'][0]['#default_value']['nid']);

    // Allow editing of the question title and status, and preview the 
    // question copy itself.
    if ($question) {

      $form['question'] = array(
        '#type' => 'fieldset',
        '#title' => 'Spørgsmålet du besvarer',
        '#tree' => TRUE,
        '#weight' => -99,
      );

      $form['question']['title'] = array(
        '#type' => 'textfield',
        '#title' => t('Title'),
        '#default_value' => $question->title,
      );

      $form['question']['body'] = array(
        '#value' => check_markup($question->body, $question->format, FALSE),
      );

      // Change status to in progress if new, otherwise use the 
      // current one.
      $status = (!isset($question->field_question_status[0]['value']) || $question->field_question_status[0]['value'] == 'new') ? 'in progress' : $question->field_question_status[0]['value'];
      $status_field = content_fields('field_question_status', $question->type);

      $form['question']['status'] = array(
        '#type' => 'select',
        '#title' => 'Status',
        '#options' => content_allowed_values($status_field),
        '#default_value' => $status,
      );

      $form['question']['edit'] = array(
        '#value' => l('Redigér spørgsmålet', 'node/' . $question->nid . '/edit', array(
          'query' => drupal_get_destination(),
        )),
      );

      $form['#submit'][] = 'vopros_qna_answer_edit_submit';
    }
    
    // Get rid of the teaser splitting functionality.
    unset($form['body_field']['teaser_js']);
    unset($form['body_field']['teaser_include']);
  }
}

/**
 * Implementation of hook_form_FORM_ID_alter().
 */
function vopros_qna_form_vopros_question_node_form_alter(&$form, &$form_state) {
  // Only allow title editing for users that can change question status 
  // (ie. editors).
  $form['title']['#access'] = user_access('edit field_question_status');

  // Get rid of the teaser splitting functionality.
  unset($form['body_field']['teaser_js']);
  unset($form['body_field']['teaser_include']);
}

/**
 * Submit handler for answer editing form.
 */
function vopros_qna_answer_edit_submit(&$form, &$form_state) {
  $question = node_load($form_state['values']['field_answer_question_ref'][0]['nid']);

  // If title or status was changed, update the question.
  if (
    $form_state['values']['question']['title'] != $question->title || 
    $form_state['values']['question']['status'] != $question->field_question_status[0]['value']
  ) {
    $question->title = $form_state['values']['question']['title'];
    $question->field_question_status[0]['value'] = $form_state['values']['question']['status'];
    
    // Make sure this is marked as a new revision with a log message 
    // denoting that this happened through answer editing. 
    $question->revision = TRUE;
    $question->log = t('Updated while editing answer “@answer_title”.', array(
      '@answer_title' => $form_state['values']['title'],
    ));

    // Save the node and let the user know it was done.
    node_save($question);
    drupal_set_message(t('Question “%name” has been updated.', array('%name' => $question->title)));

  }
}

include_once('vopros_qna.features.inc');

