<?php

/**
 * @file
 * The vopros_editorial module allows to seperate questions into editorial
 * groups, with their own type of macross etc.
 */

/**
 * Implementation of hook_init().
 */
function vopros_editorial_init() {
  drupal_add_css(drupal_get_path('module', 'vopros_editorial') . '/theme/vopros_editorial.base.css');
}



/**
 * Implements hook_enable().
 */
function vopros_editorial_enable() {
  // Create the question vopros_editorial vocabolary
  if (!taxonomy_vocabulary_machine_name_load('vopros_editorial')) {
    $vocabulary = (object) array(
      'name' => t('Editorial'),
      'machine_name' => 'vopros_editorial',
      'module' => 'vopros_editorial',
    );
    taxonomy_vocabulary_save($vocabulary);
  }
  vopros_editorial_configure_question();
}

function vopros_editorial_configure_question() {
  $type = 'vopros_question';
  $bundle = 'vopros_question';

  // Create a taxonomy term reference field
  $field_name = 'vopros_editorial';
  $field = field_info_field($field_name);
  $instance = field_info_instance($type, $field_name, $bundle);

  if (empty($field)) {
    $field = array(
      'cardinality' => 1,
      'entity_types' => array($type),
      'translatable' => FALSE,
      'assigned' => TRUE,
      'settings' => array(
        'allowed_values' => array(
          array(
            'vocabulary' => 'vopros_editorial',
            'parent' => 0,
          ),
        ),
      ),
      'field_name' => $field_name,
      'type' => 'taxonomy_term_reference',
    );
    field_create_field($field);
  }

  if (empty($instance)) {
    $instance = array(
      'entity_type' => $type,
      'bundle' => $bundle,
      'required' => FALSE,
      'settings' => array(),
      'field_name' => $field_name,
      'label' => t('Editorial'),
      'widget' => array(
        'type' => 'options_select',
      ),
      'settings' => array(),

      'display' => array(
        'default' => array(
          'label' => 'hidden',
          'type' => 'taxonomy_term_reference_link',
        ),
      ),
    );
    field_create_instance($instance);
  }
}

/**
 * Implements hook_vopros_question_activity_feed().
 */
function vopros_editorial_vopros_question_activity_feed($question, &$feed) {
  $field_info = field_info_field('vopros_editorial');
  // If we can get info on the field SQL we try to fetch the revisions
  if (isset($field_info['storage']['details']['sql']['FIELD_LOAD_REVISION'])) {
    $sql_info = $field_info['storage']['details']['sql']['FIELD_LOAD_REVISION'];
    $table = array_shift(array_keys($sql_info));
    $column = array_shift($sql_info[$table]);
    // Perform the actual query
    try {
      $query = db_select($table, 'r');
      $query->join('vopros_question_revision', 'v', 'r.revision_id = v.revision_id');
      $query->addField('r', $column, 'tid');
      $editorial_revisions = $query
        ->fields('r', array('revision_id'))
        ->fields('v', array('revision_timestamp', 'revision_uid'))
        ->condition('v.question_id', $question->question_id, '=')
        ->execute()
        ->fetchAll();
    } catch (PDOException $e) {
      // Log error, and silently fail
      watchdog(
        'vopros_editorial',
        'SQL error trying to get activity stream for question: @question_id with error message: @message',
        array('@question_id' => $question->question_id, '@message' => $e->errorInfo[2]),
        WATCHDOG_ERROR
      );
    }
    if (isset($editorial_revisions) && !empty($editorial_revisions)) {
      $tid = $editorial_revisions[0]->tid;
      foreach ($editorial_revisions as $editorial_revision) {
        // Detect any change:
        if ($editorial_revision->tid != $tid) {
          $feed['vopros_editorial_' . $editorial_revision->revision_timestamp] = array(
            '#theme' => 'vopros_editorial_field_feed',
            '#revision' => $editorial_revision,
            '#weight' => - $editorial_revision->revision_timestamp,
          );
          // Update the tid we're matching for
          $tid = $editorial_revision->tid;
        }
      }
    }
  }
}



/**
 * Implements hook_form_FORM_ID_alter().
 */
function vopros_editorial_form_vopros_sms_settings_form_alter(&$form, &$form_state) {
  // Adds editorial specific macros.
  $form['contact']['#collapsible'] = TRUE;
  $form['contact']['#collapsed'] = TRUE;
  $form['contact']['#weight'] = 2;
  $form['macros']['#collapsible'] = TRUE;
  $form['macros']['#collapsed'] = TRUE;
  $form['macros']['#weight'] = 1;

  $vocabolary = taxonomy_vocabulary_machine_name_load('vopros_editorial');
  $terms = taxonomy_term_load_multiple(NULL, array('vid' => $vocabolary->vid));

  // Loop through all the terms and copy the existin form settings, but
  // redefine the keys, so they can be used with variable_set/get.
  foreach ($terms as $term) {
    // Contact user form fields.
    $form['contact_' . $term->tid] = $form['contact'];
    $form['contact_' . $term->tid]['#title'] .= ' ' . $term->name;
    $form['contact_' . $term->tid]['#weight'] = 2;
    foreach ($form['contact_' . $term->tid] as $key => $form_field) {
      if (is_array($form_field) && isset($form_field['#type'])) {
        $new_key = $key . '_' . $term->tid;
        $form_field['#default_value'] = variable_get($new_key, '');
        $form['contact_' . $term->tid][$new_key] = $form_field;
        unset($form['contact_' . $term->tid][$key]);
      }
    }

    // Asnwer user form fields.
    $form['macros_' . $term->tid] = $form['macros'];
    $form['macros_' . $term->tid]['#title'] .= ' ' . $term->name;
    $form['macros_' . $term->tid]['#weight'] = 1;
    foreach ($form['macros_' . $term->tid] as $key => $form_field) {
      if (is_array($form_field) && isset($form_field['#type'])) {
        $new_key = $key . '_' . $term->tid;
        $form_field['#default_value'] = variable_get($new_key, '');
        $form['macros_' . $term->tid][$new_key] = $form_field;
        unset($form['macros_' . $term->tid][$key]);
      }
    }
  }

  $form['contact']['#title'] .= t(' (no editorial)');
  $form['macros']['#title'] .= t(' (no editorial)');
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function vopros_editorial_form_vopros_sms_form_alter(&$form, &$form_state) {
  // Change default value to match editorial selected macros.
  $answer = $form['answer']['#value'];
  if ($answer && $answer->question_id) {
    $answer_wrapper = entity_metadata_wrapper('vopros_answer', $answer);
    $tid = $answer_wrapper->question->vopros_editorial->value() ? $answer_wrapper->question->vopros_editorial->tid->value() : 0;
    if ($tid) {
      $form['form']['content_wrapper']['content']['#default_value'] = $content =  token_replace(variable_get('vopros_sms_answered_question_macro_' . $tid, ''), array(
         'vopros_answer' => $answer,
         'vopros_question' => $answer_wrapper->question->value(),
       ), array('sanitize' => FALSE));
    }
  }
}

/**
 * Implements hook_vopros_sms_question_contact_form_macro_alter().
 */
function vopros_editorial_vopros_sms_question_contact_form_macro_alter(&$text, $form, $key) {
  $question = $form['question']['#value'];
  $question_wrapper = entity_metadata_wrapper('vopros_question', $question);
  $tid = $question_wrapper->vopros_editorial->value() ? $question_wrapper->vopros_editorial->tid->value() : 0;
  if ($tid) {
    $new_text = variable_get($key . '_' . $tid, '');
    if ($new_text) {
      $text = $new_text;
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function vopros_editorial_form_vopros_email_settings_form_alter(&$form, &$form_state) {
  // Adds editorial specific macros.
  $form['contact']['#collapsible'] = TRUE;
  $form['contact']['#collapsed'] = TRUE;
  $form['contact']['#weight'] = 2;
  $form['macros']['#collapsible'] = TRUE;
  $form['macros']['#collapsed'] = TRUE;
  $form['macros']['#weight'] = 1;

  $vocabolary = taxonomy_vocabulary_machine_name_load('vopros_editorial');
  $terms = taxonomy_term_load_multiple(NULL, array('vid' => $vocabolary->vid));

  // Loop through all the terms and copy the existin form settings, but
  // redefine the keys, so they can be used with variable_set/get.
  foreach ($terms as $term) {
    // Contact user form fields.
    $form['contact_' . $term->tid] = $form['contact'];
    $form['contact_' . $term->tid]['#title'] .= ' ' . $term->name;
    $form['contact_' . $term->tid]['#weight'] = 2;
    // Since there is both email and subject, they are nested in a wrapper.
    foreach ($form['contact_' . $term->tid] as $reason => $wrapper) {
      if (is_array($wrapper) && isset($wrapper['#type'])) {
        foreach ($wrapper as $key => $form_field) {
          if (is_array($form_field) && isset($form_field['#type'])) {
            $new_key = $key . '_' . $term->tid;
            $form_field['#default_value'] = variable_get($new_key, '');
            $form['contact_' . $term->tid][$reason][$new_key] = $form_field;
            unset($form['contact_' . $term->tid][$reason][$key]);
          }
        }
      }
    }

    // Asnwer user form fields.
    $form['macros_' . $term->tid] = $form['macros'];
    $form['macros_' . $term->tid]['#title'] .= ' ' . $term->name;
    $form['macros_' . $term->tid]['#weight'] = 1;
    foreach ($form['macros_' . $term->tid] as $key => $form_field) {
      if (is_array($form_field) && isset($form_field['#type'])) {
        $new_key = $key . '_' . $term->tid;
        $form_field['#default_value'] = variable_get($new_key, '');
        $form['macros_' . $term->tid][$new_key] = $form_field;
        unset($form['macros_' . $term->tid][$key]);
      }
    }
  }

  $form['contact']['#title'] .= t(' (no editorial)');
  $form['macros']['#title'] .= t(' (no editorial)');
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function vopros_editorial_form_vopros_email_form_alter(&$form, &$form_state) {
  // Change default value to match editorial selected macros.
  $answer = $form['answer']['#value'];
  if ($answer && $answer->question_id) {
    $answer_wrapper = entity_metadata_wrapper('vopros_answer', $answer);
    $tid = $answer_wrapper->question->vopros_editorial->value() ? $answer_wrapper->question->vopros_editorial->tid->value() : 0;
    if ($tid) {
      $form['form']['subject']['#default_value'] = token_replace(variable_get('vopros_email_answered_question_subject_macro_' . $tid, ''), array(
        'vopros_answer' => $answer,
        'vopros_question' => $answer_wrapper->question->value(),
      ), array('sanitize' => FALSE));
      $form['form']['email_content']['#default_value'] = token_replace(variable_get('vopros_email_answered_question_macro_' . $tid, ''), array(
        'vopros_answer' => $answer,
        'vopros_question' => $answer_wrapper->question->value(),
      ), array('sanitize' => FALSE));
    }
  }
}

/**
 * Implements hook_vopros_email_question_contact_form_macro_alter().
 */
function vopros_editorial_vopros_email_question_contact_form_macro_alter(&$text, $form, $key) {
  $question = $form['question']['#value'];
  $question_wrapper = entity_metadata_wrapper('vopros_question', $question);
  $tid = $question_wrapper->vopros_editorial->value() ? $question_wrapper->vopros_editorial->tid->value() : 0;
  if ($tid) {
    $new_text = variable_get($key . '_' . $tid, '');
    if ($new_text) {
      $text = $new_text;
    }
  }
}


/**
 * Implements hook_views_default_views_alter().
 */
function vopros_editorial_views_default_views_alter(&$views) {
  $vocab = taxonomy_vocabulary_machine_name_load('vopros_editorial');
  $terms = taxonomy_term_load_multiple(FALSE, array('vid' => $vocab->vid));
  /* Filter criterion: Fields: Editorial (vopros_editorial) - tid */
  if (isset($views['vopros_question_list']) && !empty($terms)) {
    $subject = $views['vopros_question_list']->display['default']->display_options['filters']['subject_catagory_tid'];
    unset($views['vopros_question_list']->display['default']->display_options['filters']['subject_catagory_tid']);
    $views['vopros_question_list']->display['default']->display_options['filters']['vopros_editorial_tid']['id'] = 'vopros_editorial_tid';
    $views['vopros_question_list']->display['default']->display_options['filters']['vopros_editorial_tid']['table'] = 'field_data_vopros_editorial';
    $views['vopros_question_list']->display['default']->display_options['filters']['vopros_editorial_tid']['field'] = 'vopros_editorial_tid';
    $views['vopros_question_list']->display['default']->display_options['filters']['vopros_editorial_tid']['group'] = 0;
    $views['vopros_question_list']->display['default']->display_options['filters']['vopros_editorial_tid']['exposed'] = TRUE;
    $views['vopros_question_list']->display['default']->display_options['filters']['vopros_editorial_tid']['expose']['operator_id'] = 'vopros_editorial_tid_op';
    $views['vopros_question_list']->display['default']->display_options['filters']['vopros_editorial_tid']['expose']['label'] = 'with the editorial';
    $views['vopros_question_list']->display['default']->display_options['filters']['vopros_editorial_tid']['expose']['operator'] = 'vopros_editorial_tid_op';
    $views['vopros_question_list']->display['default']->display_options['filters']['vopros_editorial_tid']['expose']['use_operator'] = FALSE;
    $views['vopros_question_list']->display['default']->display_options['filters']['vopros_editorial_tid']['expose']['identifier'] = 'vopros_editorial_tid';
    $views['vopros_question_list']->display['default']->display_options['filters']['vopros_editorial_tid']['expose']['remember'] = 1;
    $views['vopros_question_list']->display['default']->display_options['filters']['vopros_editorial_tid']['expose']['multiple'] = FALSE;
    $views['vopros_question_list']->display['default']->display_options['filters']['subject_catagory_tid'] = $subject;
  }
}

/**
 * Implements hook_theme().
 */
function vopros_editorial_theme() {
  $path = drupal_get_path('module', 'vopros_editorial') . '/theme';
  return array(
    'vopros_editorial_field_feed' => array(
      'render element' => 'question',
      'file' => 'vopros_editorial.theme.inc',
      'path' => $path,
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Adds default editorial selector to the service admin form.
 */
function vopros_editorial_form_vopros_service_form_alter(&$form, &$form_state) {
  $vocab = taxonomy_vocabulary_machine_name_load('vopros_editorial');
  $terms = taxonomy_term_load_multiple(FALSE, array('vid' => $vocab->vid));

  if ($terms) {
    $options = array(
      0 => t('- None -'),
    );
    foreach ($terms as $term) {
      $options[$term->tid] = $term->name;
    }

    $form['default_editorial'] = array(
      '#type' => 'select',
      '#title' => t('Default editorial'),
      '#description' => t('New incoming questions will get this editorial.'),
      '#options' => $options,
      '#default_value' => variable_get('vopros_editorial_service_default_' . $form_state['vopros_service']->machine_name, 0),
    );

    $form['actions']['submit']['#submit'][] = 'vopros_editorial_form_vopros_service_submit';
  }
}

/**
 * Submit handler for the vopros_service_form to save default editorial.
 */
function vopros_editorial_form_vopros_service_submit($form, &$form_state) {
  if (!empty($form_state['values']['default_editorial'])) {
    variable_set('vopros_editorial_service_default_' . $form_state['vopros_service']->machine_name, $form_state['values']['default_editorial']);
  }
  else {
    variable_del('vopros_editorial_service_default_' . $form_state['vopros_service']->machine_name);
  }
}

/**
 * Implements hook_entity_delete().
 *
 * Delete the default editorial variable when deleting service entity.
 */
function vopros_editorial_entity_delete($entity, $entity_type) {
  if ($entity_type == 'vopros_service') {
    variable_del('vopros_editorial_service_default_' . $entity->machine_name);
  }
}

/**
 * Implements hook_entity_presave().
 *
 * Set default editorial value on newly created questions.
 */
function vopros_editorial_entity_presave($entity, $entity_type) {
  if ($entity_type == 'vopros_question' && $entity->is_new && !empty($entity->vopros_service) && ($tid = variable_get('vopros_editorial_service_default_' . $entity->vopros_service->machine_name, 0))) {
    $wrapper = entity_metadata_wrapper('vopros_question', $entity);
    $wrapper->vopros_editorial->set($tid);
  }
}
