<?php

/**
 * Implements hook_feeds_plugins().
 */
function vopros_mailhandler_feeds_plugins() {
  return array(
    'VoprosMailhandlerParser' => array(
      'name' => 'Vopros mailhandler IMAP stream parser',
      'description' => 'Parses an IMAP stream.',
      'handler' => array(
        'parent' => 'MailhandlerParser',
        'class' => 'VoprosMailhandlerParser',
        'file' => 'VoprosMailhandlerParser.inc',
        'path' => drupal_get_path('module', 'vopros_mailhandler') . '/plugins/mailhandler',
      ),
    ),
    'VoprosMailhandlerProcessor' => array(
      'name' => 'Vopros email processor',
      'description' => 'Create Email entities and update question status.',
      'help' => '',
      'handler' => array(
        'parent' => 'FeedsProcessor',
        'class' => 'VoprosMailhandlerProcessor',
        'file' => 'VoprosMailhandlerProcessor.inc',
        'path' => drupal_get_path('module', 'vopros_mailhandler') . '/plugins/mailhandler',
      ),
    ),
  );
}

include_once('vopros_mailhandler.features.inc');
